name: bedrock_flutter
description: A new Flutter project.

publish_to: 'none'

version: 2.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  dio: ^5.1.2
  json_serializable: ^6.7.0
  flutter_secure_storage: ^8.0.0
  package_info_plus: ^4.0.0
  json_annotation: ^4.8.1
  intl: ^0.18.1
  flutter_bloc: ^8.1.2
  jwt_decoder: ^2.0.1
  shared_preferences: ^2.1.1
  pin_code_fields: ^7.4.0
  cached_network_image: ^3.2.3
  flutter_cache_manager: ^3.3.0
  geolocator: ^9.0.2
  flutter_svg: ^2.0.6
  equatable: ^2.0.5
  flutter_libphonenumber: ^2.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  dart_jsonwebtoken: ^2.4.0
  bloc_test: ^9.1.0
  build_runner: ^2.1.4
  mockito: ^5.4.0
  
flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - test/stubs/
    
  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/inter.ttf