name: bedrock_flutter
description: A new Flutter project.

publish_to: 'none'

version: 2.1.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  dio: ^5.9.0
  flutter_secure_storage: ^9.2.4
  package_info_plus: ^8.3.1
  json_annotation: ^4.9.0
  flutter_bloc: ^9.1.1
  jwt_decoder: ^2.0.1
  shared_preferences: ^2.5.3
  pin_code_fields: ^8.0.1
  cached_network_image: ^3.4.1
  flutter_cache_manager: ^3.4.1
  geolocator: ^14.0.2
  flutter_svg: ^2.2.0
  flutter_libphonenumber: ^2.5.1
  go_router: ^16.2.0
  freezed_annotation: ^2.4.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  json_serializable: ^6.9.5
  flutter_lints: ^6.0.0
  bloc_test: ^10.0.0
  build_runner: ^2.4.12
  mockito: ^5.4.4
  freezed: ^2.5.2
  
flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - test/stubs/
    
  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/inter.ttf